config/routes.rb
SuperWhiteboard::Application.routes.draw do

  root :to => 'calendar#index'

  get "calendar/index"

  get "calendar/get_section_events_pairs"

  get "gradebook/index"

  get "gradebook/add_category"

  get "gradebook/remove_category"

  get "gradebook/add_event"

  get "gradebook/remove_event"

  get "gradebook/add_student"

  get "gradebook/remove_student"

  get "gradebook/calculate_grades"

  get "section/add_student"

  get "section/remove_student"

  get "section/add_assignment"

  get "section/remove_assignment"

  get "section/add_content"

  get "section/remove_content"

  get "section/add_professor"

  get "section/remove_professor"

  get "dragon_drop/add_event_to_section"

  get "dragon_drop/remove_event_from_section"

  get "dragon_drop/add_category"

  get "dragon_drop/remove_category"

  get "dragon_drop/add_event"

  get "dragon_drop/remove_event"

  get "dragon_drop/change_course"

  get "dragon_drop/index"

  get "dragon_drop/get_sections"

  get "dragon_drop/get_unassigned_events"

  get "dragon_drop/get_assigned_events"

  get "events/add_question"

  get "events/show", :as => :json

  resource :events, :except => [:show]

  devise_for :users

end

  # match ':controller(/:action(/:id))(.:format)'

app/controllers/dragon_drop_controller.rb
class DragonDropController < ApplicationController

  respond_to :json, :html

  def index
    @date = params[:date] ? Date.parse(params[:date]) : Date.today

    # Calculate the first day that appears on the calendar
    @calendar_start_day = @date.beginning_of_week - (@date.beginning_of_week.wday)

    user = User.first
    @courses = user.find_semester_courses(Section.date_to_semester_num(@date))
    @course = params[:course] || @courses.first
    get_unassigned_events(5)
    get_assigned_events(@course, @date)
  end

  def add_event_to_section(section_id, event_id)
    SectionEvent.create(section_id: section_id, event_id: event_id)
  end

  def remove_event_from_section(section_event_id)
    SectionEvent.where(:id => section_event_id).destroy
  end

  def add_category(user_id, weight, name)
    Category.create(:user_id => user_id, :weight => weight, :name => name)
  end

  def remove_category(category_id)
    Category.where(:id => category_id).destroy
  end

  def add_event(title, start_time=Time.now, end_time=Time.at_midnight, category_id, description, attachment)
    Event.create(:title => title, :start => start_time, :end => end_time,
                 :category_id => category_id, :description => description,
                 :attachment => attachment)
  end

  def remove_event(event_id)
    Event.where(:id => event_id).destroy
  end

  def change_course(course_id)

  end

  def get_unassigned_events(semester = 1)
    user = User.first
    @unassigned_events = user.find_courses_events(semester)
  end

  def get_assigned_events(course, date)
    #require "pry";
    user = User.first
    semester = Section.date_to_semester_num(date)
    sections_events = user.find_all_sections_and_their_events(course, semester)
    @sections = sections_events.keys.collect {|section| {:section_id => section.id, :section_name => section.long_name}}
    some_list = @sections.collect {|section| SectionEvent.find_all_by_section_id(section[:section_id])}.flatten
    @assigned_events = some_list.collect {|se|
      {:event_id => se.event_id, :section_id => se.section_id,
       :end_date => se.end_date, :event_title => Event.find_by_id(se.event_id).title}}
    #binding.pry
    respond_with @assigned_events
  end

end

app/helpers/dragon_drop_helper.rb
module DragonDropHelper
end

app/views/dragon_drop/add_category.html.erb
<h1>DragonDrop#add_category</h1>
<p>Find me in app/views/dragon_drop/add_category.html.erb</p>

app/views/dragon_drop/add_event.html.erb
<h1>DragonDrop#add_event</h1>
<p>Find me in app/views/dragon_drop/add_event.html.erb</p>

app/views/dragon_drop/add_event_to_section.html.erb
<h1>DragonDrop#add_event_to_section</h1>
<p>Find me in app/views/dragon_drop/add_event_to_section.html.erb</p>

app/views/dragon_drop/change_course.html.erb
<h1>DragonDrop#change_course</h1>
<p>Find me in app/views/dragon_drop/change_course.html.erb</p>

app/views/dragon_drop/get_assigned_events.html.erb
<script type="text/javascript">

    $(document).ready(function()
    {
        get_assigned_events();
    });
    function get_assigned_events()
    {
        $.getJSON("<%=dragon_drop_get_assigned_events_path%>", function(data)
        {
            for(var i = 0; i < data.length; i++)
            {

            }
        });
    }

</script>

app/views/dragon_drop/get_courses.html.erb
<script type="text/javascript">

    $(document).ready(function()
    {
        get_courses();
    });
    function get_courses()
    {
        $.getJSON("<%=dragon_drop_get_courses_path%>", function(data)
        {
            for(var i=0; i < temp_events.length; i++)
            {
                $("body").append("<div name='" + data[i] + "'>" + "</div>");
            }
        });
    }

</script>

app/views/dragon_drop/get_sections.html.erb
<table>
  <tr style="height:100px">
    <td style="width:100px"></td>

  <% %w(Sunday Monday Tuesday Wednesday Thursday Friday Saturday).each do |day| %>
    <td style="width:100px">
      <%= day %>
    </td>
  <% end %>
  </tr>
  <% @sections.each do |section| %>
      <tr style="height:100px">
        <td style="width:100px">
          <%= section.long_name %>
        </td>
        <% 7.times do |day| %>
           <td style="width:100px">
             <%= section.find_events_on_day(day).collect {|event| event[:event_title]} %>
           </td>
        <% end %>
      </tr>
  <% end %>
</table>

<button onclick="window.open('/events/new','Event Creator',' width=800,height=600')">Create New Event</button>

app/views/dragon_drop/get_unassigned_events.html.erb
<table>
  <% @unassigned_events.each do |course, events| %>
  <tr style="height:100px">
    <td><%= course.name %></td>
    <% events.each do |event| %>
    <td style="width:100px">
      <%= event.title %>
    </td>
    <% end %>
  </tr>
  <% end %>
</table>

app/views/dragon_drop/index.html.erb
<style>
    .event{ padding: 10px; background-color:#5f9ea0; font-size:12px; margin:4px;}
    .Event1 {width:60px; min-height:60px; margin: 2px; padding:10px; background-color:#5f9ea0; float:left; color:white;}
    #draggableContainer{ padding:20px; text-align:center; }

    .droppableDiv { width: 100px; min-height: 150px; padding: 0.5em; background-color:#C33}
    .drophover{ background-color: #1d5987;}

    table td
    {
        vertical-align:text-top;
        background: #f5f5dc;
    }

</style>

<script>
    $(function() {
        $('#draggableContainer');

        // Make unassigned divs draggable
        $($.find(".Event1")).draggable({ opacity: 0.35 , containment: 'document', cursor:'pointer', revert: true});

        // Make droppableDivs droppable!
        $($.find( ".droppableDiv")).droppable({ hoverClass: 'drophover', tolerance:'pointer',
            over: function()
            {
                //execute code you want when users hover in but havent dropped
                $('#droppableDiv').text('here');
            },
            out: function()
            {
                //execute code you want when users hover out
                $('#droppableDiv').text('out');
            },
            drop: function(event, ui)
            {
                //drop function with ui so we can receive div data
                var draggableid = ui.draggable.text();
                var draggableClass = ui.draggable.attr("class");
                var droppableDate = $(this).attr("date");
                var droppableSectionID = $(this).attr("section_id");

                $(this).append("<div class='event'>" + draggableid + "</div>");

                if(draggableid == "draggableContainer")
                {
                    //do nothing
                    alert("you shouldnt drag the container over the calender")
                }
                else
                {
                    alert("You've added " + draggableid + " to section " + droppableSectionID + ", to be assigned on " + droppableDate );
                    $( this ).addClass("alert")
                }
            }
        });
    });
</script>

<%= collection_select(:course, :id, @courses, :id, :name) %>

<div id="draggableContainer">
  <% @unassigned_events.each do |course, events| %>

      <%#= course.name %>
      <% events.each do |event| %>
          <div id="Event1" class="Event1">
            <%= event.title %>
          </div>

      <% end %>

  <% end %>
</div>

<div style="clear:both;"><br/></div>

<%= link_to "Previous Week", :controller => "dragon_drop", :action => "index", :date => (@date - 1.week).to_s %>
| <%= link_to "Next Week", :controller => "dragon_drop", :action => "index", :date => (@date + 1.week).to_s %>

<!--Create the weekly section view-->
<table>
  <tr>
    <td></td>
    <!-- Generate the days of the week -->
    <% Date::DAYNAMES.each do |day| %>
        <td style="width:100px">
          <%= day %>
        </td>
    <% end %>
  </tr>
  <!-- Go through each of the sections, and create a row for it -->
  <% @sections.each do |section| %>
      <tr>
        <td>
          <%= section[:section_name] %>
        </td>

        <% 7.times do |day| %>
            <td>
              <!-- Create the DropZone area -->
              <div class="droppableDiv" title="Today" date=<%= @calendar_start_day + day.day %> section_id="<%= section[:section_id] %>">
              .
              <!-- Add events to the DropZone -->
              <% @assigned_events.select { |event|
                event[:end_date].wday==day and event[:section_id]==section[:section_id]}.each do |event| %>
                  <div class="event" event_id="<%= event[:event_id] %>">
                    <%= event[:event_title] %>
                  </div>
              <% end %>
              </div>


            </td>

        <% end %>
      </tr>
  <% end %>
</table>

app/views/dragon_drop/remove_category.html.erb
<h1>DragonDrop#remove_category</h1>
<p>Find me in app/views/dragon_drop/remove_category.html.erb</p>

app/views/dragon_drop/remove_event.html.erb
<h1>DragonDrop#remove_event</h1>
<p>Find me in app/views/dragon_drop/remove_event.html.erb</p>

app/views/dragon_drop/remove_event_from_section.html.erb
<h1>DragonDrop#remove_event_from_section</h1>
<p>Find me in app/views/dragon_drop/remove_event_from_section.html.erb</p>