config/routes.rb
SuperWhiteboard::Application.routes.draw do

  root :to => 'calendar#index'

  get "calendar/index"

  get "calendar/get_section_events_pairs"

  get "gradebook/index"

  get "gradebook/add_category"

  get "gradebook/remove_category"

  get "gradebook/add_event"

  get "gradebook/remove_event"

  get "gradebook/add_student"

  get "gradebook/remove_student"

  get "gradebook/calculate_grades"

  get "section/add_student"

  get "section/remove_student"

  get "section/add_assignment"

  get "section/remove_assignment"

  get "section/add_content"

  get "section/remove_content"

  get "section/add_professor"

  get "section/remove_professor"

  get "dragon_drop/add_event_to_section"

  get "dragon_drop/remove_event_from_section"

  get "dragon_drop/add_category"

  get "dragon_drop/remove_category"

  get "dragon_drop/add_event"

  get "dragon_drop/remove_event"

  get "dragon_drop/change_course"

  get "dragon_drop/index"

  get "dragon_drop/get_sections"

  get "dragon_drop/get_unassigned_events"

  get "dragon_drop/get_assigned_events"

  get "events/add_question"

  get "events/show", :as => :json

  resource :events, :except => [:show]

  devise_for :users

end

  # match ':controller(/:action(/:id))(.:format)'

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
        <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
          <a class="close" data-dismiss="alert">&#215;</a>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        </div>
    <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Whiteboard", root_path, :class => 'brand' %>
<ul class="nav">
  <li>
    <%= link_to('Dragon Drop', dragon_drop_index_path) %>
  </li>
  <% if user_signed_in? %>
      <li>
        <%= link_to('Logout', destroy_user_session_path, :method=>'delete') %>
      </li>
  <% else %>
      <li>
        <%= link_to('Login', new_user_session_path)  %>
      </li>
  <% end %>
  <% if user_signed_in? %>
      <li>
        <%= link_to('Edit account', edit_user_registration_path) %>
      </li>
  <% else %>
      <li>
        <%= link_to('Sign up', new_user_registration_path)  %>
      </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "Myapp" %></title>
  <meta name="description" content="">
  <meta name="author" content="">
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= yield(:head) %>
</head>
<body>
<header class="navbar navbar-fixed-top">
  <nav class="navbar-inner">
    <div class="container">
      <%= render 'layouts/navigation' %>
    </div>
  </nav>
</header>
<div id="main" role="main">
  <div class="container">
    <div class="content">
      <div class="row">
        <div class="span12">
          <%= render 'layouts/messages' %>
          <%= yield %>
        </div>
      </div>
      <footer>
      </footer>
    </div>
  </div> <!--! end of .container -->
</div> <!--! end of #main -->
</body>
</html>